name: Deploy to Google Cloud Run
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'

    - id: 'cloudrun-deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: expenser
        source: .
        region: australia-southeast1
        suffix: '${{ github.sha }}'
        env_vars: |
          OIDC_CALLBACK_URL=https://expenser-pmc7ekho2q-ts.a.run.app/callback
          USERFILE=/data/users
        secrets: |-
          OIDC_CLIENT_ID=oidc_client_id:2
          SHEET_ID=sheet_id:1
          /data/users=users:1
