name: Deploy to Google Cloud Run
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'

    - id: 'cloudrun-deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: expenser
        source: "$GITHUB_WORKSPACE"
        region: australia-southeast1
        suffix: '${{ github.sha }}'
